apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              sed "s/__HOSTNAME__/$(hostname)/g" /tmp/template/index.html > /usr/share/nginx/html/index.html
              nginx -g 'daemon off;'
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "100Mi"
              cpu: 50m
            requests:
              memory: "64Mi"
              cpu: 25m
          readinessProbe:
            httpGet:
              path: /
              port: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: nginx-configmap
              mountPath: /tmp/template/index.html
              subPath: index.html
      volumes:
        - name: nginx-configmap
          configMap:
            name: nginx-configmap
