apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: lab
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      command: ["/bin/sh", "-c"]
      args:
        - |
          sed "s/__HOSTNAME__/$(hostname)/g" /tmp/template/index.html > /usr/share/nginx/html/index.html
          nginx -g 'daemon off;'
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "100Mi"
          cpu: 50m
        requests:
          memory: "64Mi"
          cpu: 50m
      volumeMounts:
        - name: nginx-configmap
          mountPath: /tmp/template/index.html
          subPath: index.html
  volumes:
    - name: nginx-configmap
      configMap:
        name: nginx-configmap
