# Secret chứa các thông tin nhạy cảm được sử dụng bởi Alertmanager
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: monitoring
type: Opaque # Loại Secret mặc định cho dữ liệu tùy ý
stringData:
  # Token của Bot Telegram (được cấp từ BotFather)
  telegram_bot_token: "8715216441:AAFd_wEAn8reKnSEB3tJ_yc_4lqFskVcHaI"
  # ID của Chat cá nhân hoặc Group Telegram nhận cảnh báo
  telegram_chat_id: "7524643345"