# ConfigMap chứa logic "Não bộ" của Alertmanager: Định tuyến và Gửi thông báo.
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      # Nếu trong 5 phút Prometheus không gửi lại thông tin về một Alert đang firing, Alertmanager sẽ tự động coi Alert đó là đã được giải quyết (Resolved).
      resolve_timeout: 5m

    # Cấu hình "Định tuyến" (Routing Tree): Quan trọng nhất để phân phối cảnh báo.
    route:
      group_by: ['alertname', 'severity'] # Gom nhóm các cảnh báo giống nhau để tránh bắn tin nhắn rác (spam)
      group_wait: 30s        # Chờ 30 giây để gom các cảnh báo phát sinh cùng lúc
      group_interval: 5m     # Thời gian chờ trước khi gửi tiếp các cảnh báo mới trong cùng một nhóm
      repeat_interval: 4h    # Khoảng thời gian gửi lại cảnh báo nếu vấn đề vẫn chưa được xử lý (4 giờ gửi 1 lần)
      
      # Gửi toàn bộ cảnh báo về receiver mặc định là Telegram
      receiver: telegram

    # Định nghĩa các "Đầu nhận" (Receivers)
    receivers:
      - name: telegram
        telegram_configs:
          # Bảo mật: Không ghi trực tiếp Token vào đây. Token được đọc từ file nằm trong Volume Secret đã mount.
          - bot_token_file: /etc/alertmanager/secrets/telegram_bot_token
            # ID của Chat/Group Telegram nơi Bot sẽ bắn tin nhắn tới.
            chat_id: 7524643345
            # Đảm bảo nhận được thông báo cả khi hệ thống lỗi và khi hệ thống "Hồi phục" (Resolved).
            send_resolved: true
            # Định dạng tin nhắn (Có thể tùy chỉnh bằng Template nếu cần)
            parse_mode: 'HTML'
