# Secret: Nơi lưu giữ các dữ liệu "nhạy cảm" (Mật khẩu, Token).
# Dữ liệu trong Secret sẽ được mã hóa Base64 khi lưu trữ trong Etcd của K8s.
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: monitoring
type: Opaque # Loại dữ liệu tùy chỉnh (Key-Value)
stringData:
  # Mã Token định danh của Bot Telegram - Cần giữ bí mật tuyệt đối.
  telegram_bot_token: "8715216441:AAFd_wEAn8reKnSEB3tJ_yc_4lqFskVcHaI"
  # Mã số định danh của Chat/Group nhận tin - Giúp Bot biết gửi tin đi đâu.
  telegram_chat_id: "7524643345"