apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# [1. Danh sách Resources]
# Khai báo tất cả các Manifests của Alertmanager sẽ được Kustomize gộp lại
resources:
  - alertmanager-config.yaml
  - alertmanager-headless-svc.yaml
  - alertmanager-pdb.yaml
  - alertmanager-secret.yaml
  - alertmanager-sts.yaml
  - alertmanager-svc.yaml
