# Secret: Lưu trữ mật khẩu đăng nhập và thông tin kết nối Database.
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
type: Opaque
stringData:
  # Mật khẩu quản trị viên (Admin) khi đăng nhập lần đầu vào Web
  GF_SECURITY_ADMIN_PASSWORD: "12345678"
  # Mật khẩu để Grafana kết nối vào cơ sở dữ liệu PostgreSQL
  GF_DATABASE_PASSWORD: "grafana_pwd123"