# Service Headless (ClusterIP: None) cho Node Exporter.
# KHÁC BIỆT: Thay vì tạo 1 IP duy nhất, Service này trả về danh sách IP của TOÀN BỘ các Pod trên mọi Node.
# Prometheus dùng danh sách này để kết nối tới từng Node vật lý và lấy métrics phần cứng riêng biệt.
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  # Chế độ Headless: Không tạo Virtual IP đại diện.
  clusterIP: None
  selector:
    app: node-exporter # Kết nối tới các Pod Node Exporter trên toàn cụm
  ports:
    - name: metrics
      port: 9100        # Port mà Prometheus sẽ gọi tới
      targetPort: 9100  # Port Container
      protocol: TCP