# Node Exporter: "Cảm biến phần cứng" của Cluster.
# Sử dụng DaemonSet để đảm bảo MỖI máy chủ (Node) trong Cluster đều chạy 1 bản sao duy nhất.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      # hostNetwork: Cho phép Node Exporter dùng chung card mạng với Server thật. 
      # Cần thiết để lấy đúng các métrics về lưu lượng mạng trên Node.
      hostNetwork: true
      
      # hostPID: Cho phép nhìn thấy toàn bộ tiến trình đang chạy trên Node vật lý.
      hostPID: true
      
      # Tolerations: Quy tắc cho phép Pod chạy lên cả các Node Master/Control-plane (vốn thường bị cấm chạy ứng dụng).
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      
      containers:
      - name: node-exporter
        image: prom/node-exporter:v1.8.1
        ports:
          - name: metrics
            containerPort: 9100 # Cổng chuẩn của Node Exporter
        args:
          # Chỉ định đường dẫn /host (được mount từ node thật) để quét tài nguyên ổ đĩa và hệ thống.
          - "--path.rootfs=/host"
          - "--path.procfs=/host/proc"
          - "--path.sysfs=/host/sys"

        # Kiểm tra sức khỏe của exporter
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9100
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9100
          initialDelaySeconds: 10
          periodSeconds: 15

        # Tài nguyên tiêu tốn (rất nhỏ)
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"

        volumeMounts:
          - name: root
            mountPath: /host     # Mount thư mục gốc của Node vật lý vào container
            readOnly: true       # Bảo mật: Chỉ cho phép đọc, không cho xóa file trên Node thật
            mountPropagation: HostToContainer
      volumes:
        - name: root
          hostPath:
            path: /              # Lấy từ thư mục gốc của server Linux