apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# [1. Danh sách Resources]
resources:
  - prometheus-config.yaml
  - prometheus-pdb.yaml
  - prometheus-rbac.yaml
  - prometheus-sts.yaml
  - prometheus-svc.yaml
