# 1. Service Headless (ClusterIP: None)
# Mục đích: Không cấp IP ảo (VIP), mà trả về IP trực tiếp của các Pod.
# Cần thiết cho StatefulSet để các Pod có thể định danh DNS theo dạng: prometheus-0.prometheus-headless, prometheus-1.prometheus-headless
apiVersion: v1
kind: Service
metadata:
  name: prometheus-headless
  namespace: monitoring
  labels:
    app: prometheus
spec:
  clusterIP: None # Chế độ Headless
  ports:
    - name: web
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus # Liên kết với các Pod có nhãn app: prometheus
---
# 2. Service ClusterIP tiêu chuẩn
# Mục đích: Tạo một điểm truy cập duy nhất (Virtual IP) cho các ứng dụng khác (như Grafana) kết nối tới Prometheus.
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: 9090 # Chuyển traffic vào port 9090 của Pod
  selector:
    app: prometheus
  type: ClusterIP # Chỉ truy cập được từ bên trong Cluster
